### ISSUE TITLE
Getting Exception in thread "Thread-5" org.openqa.selenium.WebDriverException: NULL_OUTPUT_STREAM

### ISSUE THREAD

**Issue by rajajan09** [Linus789/DeepLTranslator#10] opened 2021-08-23 17:40 UTC
When I try to run below code

`public class Translate1 {

	public static void main(String[] args) {
		DeepLConfiguration deepLConfiguration = new DeepLConfiguration.Builder()
				.setTimeout(Duration.ofSeconds(10))
				.setRepetitions(3)
				.setRepetitionsDelay(retryNumber -> Duration.ofMillis(3000 + 5000 * retryNumber))
				.setPostProcessing(true)
				.build();

		DeepLTranslator deepLTranslator = new DeepLTranslator(deepLConfiguration);

		try {
			String translation = deepLTranslator.translate("I ran into a similar problem yesterday.", Language.AUTO_DETECT, Language.GERMAN);
			System.out.println(translation);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}`

getting below error:
Exception in thread "Thread-5" org.openqa.selenium.WebDriverException: NULL_OUTPUT_STREAM
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T20:55:26'
System info: host: 'DESKTOP-C0OB8V0', ip: '192.168.225.52', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_275'
Driver info: driver.version: JBrowserDriver
	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:136)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.lambda$launchProcess$2(JBrowserDriver.java:475)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchFieldError: NULL_OUTPUT_STREAM
	at org.zeroturnaround.exec.ProcessExecutor.redirectOutput(ProcessExecutor.java:394)
	at org.zeroturnaround.exec.ProcessExecutor.<init>(ProcessExecutor.java:149)
	at com.machinepublishers.jbrowserdriver.JBrowserDriver.lambda$launchProcess$2(JBrowserDriver.java:427)
	... 1 more

Should I follow or install anything to run the deepl Translator?

**Comment by DreamCloudProject** [comment] 2021-08-24 13:36
I have the same issue.

2021-08-24 15:31:51.023 ERROR 18428 --- [mTaskExecutor-1] c.m.m.services.TranslationAdminService   : Could not launch browser.
Build info: version: '4.0.0-alpha-2', revision: 'f148142cf8', time: '2019-07-01T20:55:26'
System info: host: 'MSI-GS65', ip: '192.168.1.236', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.7'
Driver info: driver.version: JBrowserDriver
[2021-08-24T13:31:51.345] java.lang.NoClassDefFoundError: com/sun/webkit/network/CookieManager
[2021-08-24T13:31:51.345] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:80)
[2021-08-24T13:31:51.345] Caused by: java.lang.ClassNotFoundException: com.sun.webkit.network.CookieManager
[2021-08-24T13:31:51.346] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[2021-08-24T13:31:51.346] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[2021-08-24T13:31:51.346] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[2021-08-24T13:31:51.347] 	... 1 more

**Comment by Linus789** [comment] 2021-08-25 09:27
This issue should be fixed with the newest release, since this project now uses the ChromeDriver instead of the JBrowserDriver.

> I have the same issue.

That is another issue. You are using Java 11, but the JBrowserDriver only supports Java 8. With the ChromeDriver both versions should be supported now.

**Closed by Linus789** 2021-08-25 09:27 UTC
